import { Project } from './types'

export const projects: Project[] = [
  {
    id: '1',
    slug: 'villa-laimoun',
    title: 'Villa Laimoun',
    category: 'villa',
    image: '/images/villa-luxury.png',
    description: 'Contemporary villa interior redesign with emphasis on open living and natural materials. Complete space planning and custom joinery.',
    location: 'Casablanca',
    year: 2023,
    featured: true,
    images: ['/images/villa-laimoun.jpg', '/images/project-detail-1.jpg', '/images/villa-luxury.png'],
    challenge: 'Create an open living space that maintains privacy while maximizing natural light.',
    solution: 'Strategic placement of sliding partitions and layered lighting systems.',
    designProcess: 'Comprehensive 2D and 3D conceptualization with material sampling.',
    materials: ['Oak flooring', 'Marble surfaces', 'Custom cabinetry', 'Italian lighting fixtures', 'Natural textiles'],
  },
  {
    id: '2',
    slug: 'villa-temara',
    title: 'Villa Temara',
    category: 'villa',
    image: '/images/villa-temara.jpg',
    description: 'Luxury beach villa with integrated living spaces. Custom millwork and premium finishes throughout.',
    location: 'Temara',
    year: 2023,
    featured: true,
    images: ['/images/project-detail-2.jpg', '/images/villa-luxury.png', '/images/villa-temara.jpg'],
    challenge: 'Blend coastal aesthetics with functional luxury.',
    solution: 'Custom built-in elements and seamless indoor-outdoor transitions.',
    designProcess: 'Coastal design research with bespoke 3D visualization.',
    materials: ['Cedarwood', 'Limestone', 'Brass fixtures', 'Natural linen', 'Glass walls'],
  },
  {
    id: '3',
    slug: 'hall-office',
    title: 'Hall Office Casablanca',
    category: 'office',
    image: '/images/hall-office.jpg',
    description: 'Modern professional office space with flexible work zones. High-end finishes and acoustic optimization.',
    location: 'Casablanca',
    year: 2022,
    featured: true,
    images: ['/images/office-space.jpg', '/images/project-detail-1.jpg', '/images/design-process.jpg'],
    challenge: 'Create multiple work zones without losing spatial cohesion.',
    solution: 'Modular design with acoustic panels and flexible partitioning.',
    designProcess: 'Collaborative process with detailed site supervision.',
    materials: ['Polished concrete floors', 'Walnut paneling', 'Acoustic fabric', 'Glass dividers', 'LED systems'],
  },
  {
    id: '4',
    slug: 'bank-branch-one',
    title: 'Bank Branch - Casablanca',
    category: 'bank',
    image: '/images/bank-interior.png',
    description: 'Banking space renovation with customer-centric design. Security integrated with elegance.',
    location: 'Casablanca',
    year: 2022,
    featured: false,
    images: ['/images/bank-branch-1.jpg', '/images/bank-interior.png', '/images/project-detail-2.jpg'],
    challenge: 'Balance security requirements with welcoming customer experience.',
    solution: 'Elegant integration of security with premium finishes and spatial design.',
    designProcess: 'Detailed planning with institutional consultation.',
    materials: ['Marble reception', 'Chrome finishes', 'Walnut furniture', 'Security glass', 'Professional lighting'],
  },
  {
    id: '5',
    slug: 'luxury-kitchen',
    title: 'Luxury Kitchen Design',
    category: 'kitchen',
    image: '/images/kitchen-bespoke.png',
    description: 'Bespoke kitchen with Italian cabinetry, marble surfaces, and integrated appliances.',
    location: 'Casablanca',
    year: 2023,
    featured: false,
    images: ['/images/luxury-kitchen.jpg', '/images/kitchen-bespoke.png', '/images/design-process.jpg'],
    materials: ['Italian cabinetry', 'Marble countertops', 'Integrated appliances', 'Gold fixtures', 'Engineered wood'],
  },
  {
    id: '6',
    slug: 'residential-interior',
    title: 'Residential Interior',
    category: 'residential',
    image: '/images/residential.jpg',
    description: 'Complete home interior design with modern minimalist aesthetic and warm tones.',
    location: 'Casablanca',
    year: 2023,
    featured: false,
    images: ['/images/hero-main.png', '/images/residential.jpg', '/images/project-detail-1.jpg'],
    materials: ['Natural oak', 'Taupe fabrics', 'Marble accents', 'Brass fixtures', 'Natural stone'],
  },
  {
    id: '7',
    slug: 'furniture-collection',
    title: 'Custom Furniture Collection',
    category: 'furniture',
    image: '/images/furniture.jpg',
    description: 'Handcrafted furniture pieces designed for residential and commercial spaces.',
    location: 'Casablanca',
    year: 2023,
    featured: false,
    images: ['/images/furniture.jpg', '/images/design-process.jpg', '/images/project-detail-1.jpg'],
    materials: ['Solid walnut', 'Leather upholstery', 'Hand-stitched details', 'Brass hardware', 'Custom fabrics'],
  },
  {
    id: '8',
    slug: 'office-renovation',
    title: 'Office Space Renovation',
    category: 'office',
    image: '/images/office-space.jpg',
    description: 'Complete office renovation with focus on employee wellbeing and productivity.',
    location: 'Casablanca',
    year: 2022,
    featured: false,
    images: ['/images/office-space.jpg', '/images/hall-office.jpg', '/images/design-process.jpg'],
    materials: ['Epoxy flooring', 'Oak partitions', 'Green walls', 'Natural lighting', 'Ergonomic furniture'],
  },
]

export const getFeaturedProjects = () => projects.filter(p => p.featured)

export const getProjectsByCategory = (category: Project['category']) =>
  projects.filter(p => p.category === category)

export const getProjectBySlug = (slug: string) =>
  projects.find(p => p.slug === slug)
